apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==  # base64 encoded value of 'root'
  MYSQL_DATABASE: dGVzdF9kYg==  # base64 encoded value of 'test_db'
